- Naenio.xcodeproj/project.pbxproj
- Naenio/Sources/Home/Card/CardView.swift
- Naenio/Sources/Home/Comment/CommentRepliesView.swift
- Naenio/Sources/Home/Comment/CommentRepliesViewModel.swift
- Naenio/Sources/Home/Full/FullView.swift
- Naenio/Sources/Home/Vote/VotesView.swift
- Naenio/Utils/Network/Service/RequestService.swift
Full view에 댓글과 신고, 공유 시트를 추가했습니다
> [Feature] Full view and comment

- Naenio.xcodeproj/project.pbxproj
- Naenio/Resources/Views/Sheet/LowSheetNotification.swift
- Naenio/Resources/Views/Toast/ToastInformation.swift
- Naenio/Resources/Views/View + Exetension.swift
- Naenio/Sources/Home/Card/CardView.swift
- Naenio/Sources/Home/Comment/CommentContentCell.swift
- Naenio/Sources/Home/Comment/CommentRepliesView.swift
- Naenio/Sources/Home/Comment/CommentView.swift
- Naenio/Sources/Home/Comment/CommentViewModel.swift
- Naenio/Sources/Home/Comment/Model/CommentModel.swift
- Naenio/Sources/Home/Full/FullView.swift
- Naenio/Sources/Home/HomeView.swift
- Naenio/Sources/Main/MainView.swift
- Naenio/Sources/Main/ReportAndShareSheetView.swift
- Naenio/Utils/User/UserManager.swift
- 삭제하기 기능 붙이고(노 API)
- 토스트도 붙임
- #86, #87, #88, 
- #118 
- #106
> [Feature] Delete/report sheet(toast)

- Naenio/Sources/Curation/CurationView.swift
- Naenio/Sources/Curation/ThemeView.swift
- Naenio/Sources/Main/TabContentView.swift
테마에서 댓글, 풀 뷰 참조시 튕기던 문제를 해결했습니다.
코드만 몇 줄 더하면 되는 거라 리뷰가 필요할 것 같진 않은데 어떤 작업 하시는지 몰라서 일단 머지는 미뤄놨습니다.
- #117
> [Fix] Connect env object to theme views

- Naenio/Resources/Views/UITextView/TextVIew/UITextViewRepresentable.swift
- Naenio/Resources/Views/UITextView/TextVIew/WrappedTextView.swift
> [Fix] Text field's text position in new post

- Naenio.xcodeproj/project.pbxproj
- Naenio/Resources/Views/Toast/Toast.swift
- Naenio/Sources/Common/Model/ReportManager.swift
- Naenio/Sources/Common/Model/ReportRequestModel.swift
- Naenio/Sources/Home/Card/CardView.swift
- Naenio/Sources/Home/Card/CardViewModel.swift
- Naenio/Sources/Home/Comment/Model/CommentType.swift
- Naenio/Sources/Home/Full/FullView.swift
- Naenio/Sources/Home/Full/FullViewModel.swift
- Naenio/Sources/Main/MainView.swift
- Naenio/Utils/Network/API/NaenioAPI+Method.swift
- Naenio/Utils/Network/API/NaenioAPI+Path.swift
- Naenio/Utils/Network/API/NaenioAPI+Task.swift
- Naenio/Utils/Network/API/NaenioAPI.swift
신고 API 붙이기. 지금은 서버에서 `500`내려옴
- 신고 API 추가
- 신고 버튼에 신고 기능 연결
- #85
> [Feature] Report

- Naenio.xcodeproj/project.pbxproj
- Naenio/Resources/Views/Toast/Toast.swift
- Naenio/Sources/Home/Comment/CommentContentCell.swift
- Naenio/Sources/Home/Comment/CommentContentCellViewModel.swift
- Naenio/Sources/Home/Comment/CommentRepliesView.swift
- Naenio/Sources/Home/Comment/CommentView.swift
- Naenio/Sources/Home/Comment/CommentViewModel.swift
- Naenio/Sources/Home/Comment/Model/CommentModel.swift
- Naenio/Sources/Home/HomeView.swift
- Naenio/Sources/Home/Vote/VotesView.swift
- Naenio/Utils/Network/API/NaenioAPI+Method.swift
- Naenio/Utils/Network/API/NaenioAPI+Path.swift
- Naenio/Utils/Network/API/NaenioAPI+Task.swift
- Naenio/Utils/Network/API/NaenioAPI.swift
> [Feature] Comment like

- Naenio.xcodeproj/project.pbxproj
- Naenio/Sources/Curation/ThemeView.swift
- Naenio/Sources/Home/Comment/CommentContentCell.swift
- Naenio/Sources/Home/Comment/CommentRepliesView.swift
- Naenio/Sources/Home/Comment/CommentRepliesViewModel.swift
- Naenio/Sources/Home/Comment/CommentView.swift
- Naenio/Sources/Home/Comment/CommentViewModel.swift
- Naenio/Sources/Home/Comment/Protocol/Commentable.swift
- Naenio/Sources/Home/Full/FullView.swift
- Naenio/Sources/Home/HomeView.swift
- #123
- 삭제 시 처리는 나중에 다시 구현해야 함
> [Feature] Commet count

- Naenio.xcodeproj/project.pbxproj
- Naenio/Sources/MyPage/Cell/MyPageNavigationCell.swift
- Naenio/Sources/MyPage/Notice/Model/Notice.swift
- Naenio/Sources/MyPage/Notice/Model/NoticeResponseModel.swift
- Naenio/Sources/MyPage/Notice/NoticeDetailView.swift
- Naenio/Sources/MyPage/Notice/NoticeView.swift
- Naenio/Sources/MyPage/Notice/NoticeViewModel.swift
- Naenio/Utils/Network/API/NaenioAPI+Method.swift
- Naenio/Utils/Network/API/NaenioAPI+Path.swift
- Naenio/Utils/Network/API/NaenioAPI+Task.swift
- Naenio/Utils/Network/API/NaenioAPI.swift
- Naenio/Utils/Network/Service/RequestService.swift
> [Feature] Notice API

- Naenio.xcodeproj/project.pbxproj
- Naenio/Sources/Home/Comment/CommentContentCell.swift
- Naenio/Sources/Home/Comment/CommentContentCellViewModel.swift
- Naenio/Sources/Home/Comment/CommentRepliesView.swift
- Naenio/Sources/Home/Comment/CommentRepliesViewModel.swift
- Naenio/Sources/Home/Comment/CommentView.swift
- Naenio/Sources/Home/Comment/CommentViewModel.swift
> [Feature] Delete comment & replies

- Naenio.xcodeproj/project.pbxproj
- Naenio/Resources/Views/Toast/ToastInformation.swift
- Naenio/Resources/Views/View + Exetension.swift
- Naenio/Sources/Home/Full/FullView.swift
- Naenio/Sources/Home/Full/OpenedByLinkFullView.swift
- Naenio/Sources/Home/Models/Posts/SinglePostResponseModel.swift
- Naenio/Sources/Home/NewPost/NewPostView.swift
- Naenio/Sources/MyPage/Comments/Model/MyComment.swift
- Naenio/Sources/MyPage/Comments/Model/MyCommentRequest.swift
- Naenio/Sources/MyPage/Comments/Model/MyCommentResponseModel.swift
- Naenio/Sources/MyPage/Comments/MyCommentCell.swift
- Naenio/Sources/MyPage/Comments/MyCommentView.swift
- Naenio/Sources/MyPage/Comments/MyCommentViewModel.swift
- Naenio/Sources/MyPage/MyPageView.swift
- Naenio/Utils/Network/API/NaenioAPI+Method.swift
- Naenio/Utils/Network/API/NaenioAPI+Path.swift
- Naenio/Utils/Network/API/NaenioAPI+Task.swift
- Naenio/Utils/Network/API/NaenioAPI.swift
- Naenio/Utils/Network/Service/RequestService.swift
- #111
- #140
- 풀 뷰로 게시글을 보인 후 댓글 보이기
> [Feature] Connect my comment API

- Naenio/Sources/Home/Comment/CommentRepliesView.swift
- Naenio/Sources/Home/Comment/CommentRepliesViewModel.swift
- Naenio/Sources/Home/Comment/CommentView.swift
- Naenio/Sources/Home/Comment/CommentViewModel.swift
> [Bug] 댓글 및 대댓글 paging 기능 안되는 현상 수정

- Naenio/Sources/LogIn/LoginView.swift
- Naenio/Sources/LogIn/LoginViewModel.swift
- Naenio/Sources/MyPage/Cell/MyPageAuthCell.swift
- Naenio/Sources/MyPage/MyPageView.swift
- Naenio/Utils/Network/API/NaenioAPI.swift
- Naenio/Utils/User/UserManager.swift
> Fix/login error(#153)

- Naenio.xcodeproj/project.pbxproj
- Naenio/Sources/LogIn/LoginView.swift
- Naenio/Utils/Network/API/NaenioAPI+Request.swift
- Naenio/Utils/Network/Constants/NaenioAPIHeaderInformation.swift
> [Fix] Token's unchanged when login with another auth type

- Naenio/Resources/Views/Buttons/VoteButton.swift
- Naenio/Sources/Home/HomeView.swift
> [Fix] Vote's text alignment

- Naenio/Resources/Views/UITextView/TextVIew/UITextViewRepresentable.swift
- Naenio/Resources/Views/UITextView/TextVIew/WrappedTextView.swift
- Naenio/Sources/Home/NewPost/NewPostView.swift
> [Fix] Block newline in new post

- Naenio/Sources/Curation/CurationView.swift
- Naenio/Sources/Home/Comment/CommentRepliesView.swift
- Naenio/Sources/Home/Comment/CommentView.swift
- Naenio/Sources/MyPage/ProfileChange/ProfileChangeView.swift
- Naenio/Supporting files/NaenioApp.swift
- #164 
- #165 
- #166 
- #167
> [Fix] UI QA requirements

- Naenio.xcodeproj/xcuserdata/lee.xcuserdatad/xcschemes/xcschememanagement.plist
- Naenio/Sources/Curation/CurationView.swift
- Naenio/Sources/Main/TabContentView.swift
- Naenio/Supporting files/NaenioApp.swift
- #144 
- 문제는 고쳐졌는데 이제 풀 뷰로 넘어갈 때 탭 바가 안 가려집니다.
- SwiftUI 고유 버그라 당장은 고칠 방법이 요원해서 그냥 `NavigationView`를 탭바 안으로 가져왔습니다.(원래는 밖에 있었음)
- ref: https://stackoverflow.com/questions/69330053/navigation-tabview-sheet-broken-in-ios-15
- 린트는 마스터 머지 전에 한 번에 고치는 것으로,, 괜찮나요.
> [Fix] Fullview pop back error

- Naenio/Sources/Curation/ThemeView.swift
- Naenio/Sources/Curation/ThemeViewModel.swift
- ~#169~ -> 협의 완료(기본 스피너 사용)
- 테마뷰에서 로딩인디케이터 겹치는 문제
스피너 색이랑 크기는 나중에 의견 받아서 다시 고치는 걸로 할 것 같아요.
> [Fix] Loading indicator related jobs

- Naenio.xcodeproj/project.pbxproj
- Naenio/Sources/Curation/RandomThemeView.swift
- Naenio/Sources/Curation/ThemeView.swift
- Naenio/Sources/Home/Card/CardView.swift
- Naenio/Sources/Home/Comment/CommentContentCell.swift
- Naenio/Sources/Home/Comment/CommentRepliesView.swift
- Naenio/Sources/Home/Comment/CommentView.swift
- Naenio/Sources/Home/Full/FullView.swift
- Naenio/Sources/Home/Full/OpenedByLinkFullView.swift
- Naenio/Sources/Home/HomeView.swift
- Naenio/Sources/Home/NewPost/NewPostView.swift
- Naenio/Sources/Home/Vote/VotesView.swift
- Naenio/Sources/LogIn/LoginView.swift
- Naenio/Sources/MyPage/Comments/MyCommentView.swift
- Naenio/Sources/MyPage/MyPageView.swift
- Naenio/Sources/MyPage/Notice/NoticeView.swift
- Naenio/Sources/MyPage/ProfileChange/ProfileChangeView.swift
- Naenio/Utils/Network/API/NaenioAPI+Error.swift
- #141 
//TODO: 현재는 rest api 네트워킹 요청 시점에만 error를 잡고 있다면, 추후 timeout 및 internet connection에 시점에 대한 에러 붙이기 필요
//FIXME: 네트워킹 통신 시 오는 error code에 대해 정리 필요(현재는 nil값으로 받아 오는 중)
> [Feature] error에 따른 alert창 붙이기

- Naenio.xcodeproj/project.pbxproj
- Naenio/Resources/Alert/SystemAlert + Extension.swift
- Naenio/Resources/System/Notification + Extension.swift
- Naenio/Resources/System/Publishers + Extension.swift
- Naenio/Resources/Views/EmptyResultView.swift
- Naenio/Resources/Views/Toast/ToastAlert.swift
- Naenio/Resources/Views/Toast/ToastInformation.swift
- Naenio/Resources/Views/View + Exetension.swift
- Naenio/Sources/Home/Card/CardView.swift
- Naenio/Sources/Home/Card/CardViewModel.swift
- Naenio/Sources/Home/Comment/CommentContentCell.swift
- Naenio/Sources/Home/Comment/CommentRepliesView.swift
- Naenio/Sources/Home/Comment/CommentView.swift
- Naenio/Sources/Home/Vote/VotesView.swift
- Naenio/Sources/Main/MainView.swift
- Naenio/Supportings/NaenioApp.swift
- Naenio/Utils/Network/API/NaenioAPI+Error.swift
- Naenio/Utils/Network/Monitor/NetworkStatusMonitor.swift
> [Feature] Offline handling

- Naenio/Supportings/Launch Screen.storyboard
> [FIX] splash 이미지 해상도 대응 추가
